### PR TITLE
Support local rpath by explicitly targeting the package directory

### PR DESCRIPTION
**Pull request by lbeder**

### CODE REVIEW

**Comment by lbeder** [comment]
@netoneko good to go

**Comment by netoneko** [comment]
@lbeder amazing!

**Comment by netoneko** [comment]
@lbeder unfortunately, this fix does not work.

After I install the package through pip:

```
pip install /Users/kirill/GitHub/orbs-client-sdk-python --no-cache -v --no-clea
```

`find /usr/local/lib/python2.7/site-packages/orbs_client` gives us

```
/usr/local/lib/python2.7/site-packages/orbs_client
/usr/local/lib/python2.7/site-packages/orbs_client/http_client.py
/usr/local/lib/python2.7/site-packages/orbs_client/__init__.py
/usr/local/lib/python2.7/site-packages/orbs_client/http_client.pyc
/usr/local/lib/python2.7/site-packages/orbs_client/pycrypto.so
/usr/local/lib/python2.7/site-packages/orbs_client/__init__.pyc
/usr/local/lib/python2.7/site-packages/orbs_client/contract.py
/usr/local/lib/python2.7/site-packages/orbs_client/contract.pyc
/usr/local/lib/python2.7/site-packages/orbs_client/libcryptosdk.dylib
```

Then

```
cd /tmp
python
import orbs_client
```

We expect to import the library successfully. Instead, we get an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/orbs_client/__init__.py", line 2, in <module>
    from contract import Contract
  File "/usr/local/lib/python2.7/site-packages/orbs_client/contract.py", line 3, in <module>
    from pycrypto import Address
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/orbs_client/pycrypto.so, 2): Library not loaded: @rpath/libcryptosdk.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/orbs_client/pycrypto.so
  Reason: image not found
```

Upon further inspection:

`otool -l /usr/local/lib/python2.7/site-packages/orbs_client/pycrypto.so` will return

```
Load command 14
          cmd LC_RPATH
      cmdsize 104
         path /private/var/folders/x5/1c16f35j4qs60d48y5qvg8d80000gn/T/pip-req-build-W8KUWH/orbs_client (offset 12)
```

Which means `@rpath` is not `.` and is in fact absolute path to temporary build location.

**Comment by lbeder** [comment]
Please try to delete everything and rebuild, but it doesn't work, that
means that we'd need to have a special fix for the pip flow. Let's schedule
some time and work on it together.

**Pull request closed without merging**
